/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Altitudeordepthtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Altitudeordepthtype"
(
	"AltitudeordepthtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Altitudeordepthtype" ADD CONSTRAINT "PK_Altitudeordepthtype"
	PRIMARY KEY ("AltitudeordepthtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Altitudeordepthtype"
	IS 'Codelist for altitude/depth classifications'
;