/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Applicationareatype" CASCADE
;

/* Create Tables */

CREATE TABLE "Applicationareatype"
(
	"ApplicationareatypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Applicationareatype" ADD CONSTRAINT "PK_Applicationareatype"
	PRIMARY KEY ("ApplicationareatypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Applicationareatype"
	IS 'Application Area codelist

note to group:
14 application areas in WMO Core Metadata profile
Also comparable list in WIGOS - to review.'
;