/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Application-area" CASCADE
;

/* Create Tables */

CREATE TABLE "Application-area"
(
	"Application-areaID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Application-area" ADD CONSTRAINT "PK_Application-area"
	PRIMARY KEY ("Application-areaID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Application-area"
	IS 'The value(s) for applicationArea shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/ApplicationArea.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;