/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Climatezonetype" CASCADE
;

/* Create Tables */

CREATE TABLE "Climatezonetype"
(
	"ClimatezonetypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Climatezonetype" ADD CONSTRAINT "PK_Climatezonetype"
	PRIMARY KEY ("ClimatezonetypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Climatezonetype"
	IS '4-07 Climate Zone '
;