/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Communication-method" CASCADE
;

/* Create Tables */

CREATE TABLE "Communication-method"
(
	"Communication-methodID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Communication-method" ADD CONSTRAINT "PK_Communication-method"
	PRIMARY KEY ("Communication-methodID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Communication-method"
	IS 'The value for communicationMethod, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/DataCommunicationMethod.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;