/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Controlstandardtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Controlstandardtype"
(
	"ControlstandardtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Controlstandardtype" ADD CONSTRAINT "PK_Controlstandardtype"
	PRIMARY KEY ("ControlstandardtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Controlstandardtype"
	IS '5-08 Codelist for types of Control Standards'
;