/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Coordinatereferencesystemtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Coordinatereferencesystemtype"
(
	"CoordinatereferencesystemtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Coordinatereferencesystemtype" ADD CONSTRAINT "PK_Coordinatereferencesystemtype"
	PRIMARY KEY ("CoordinatereferencesystemtypeID")
;