/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Coordinatesreferencesystemtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Coordinatesreferencesystemtype"
(
	"CoordinatesreferencesystemtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Coordinatesreferencesystemtype" ADD CONSTRAINT "PK_Coordinatesreferencesystemtype"
	PRIMARY KEY ("CoordinatesreferencesystemtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Coordinatesreferencesystemtype"
	IS 'Coordinate reference system codelist'
;