/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Data-format" CASCADE
;

/* Create Tables */

CREATE TABLE "Data-format"
(
	"Data-formatID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Data-format" ADD CONSTRAINT "PK_Data-format"
	PRIMARY KEY ("Data-formatID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Data-format"
	IS 'The value for dataFormat, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/DataFormat.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;