/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Datacommunicationmethodtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Datacommunicationmethodtype"
(
	"DatacommunicationmethodtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Datacommunicationmethodtype" ADD CONSTRAINT "PK_Datacommunicationmethodtype"
	PRIMARY KEY ("DatacommunicationmethodtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Datacommunicationmethodtype"
	IS 'Data Communication method'
;