/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Deployment-valid" CASCADE
;

/* Create Tables */

CREATE TABLE "Deployment-valid"
(
	"Deployment-validID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Deployment-valid" ADD CONSTRAINT "PK_Deployment-valid"
	PRIMARY KEY ("Deployment-validID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Deployment-valid"
	IS 'XML encodings of Deployment shall conform to the XML form for Deployment specified in the WMDR XML Schema.'
;