/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Deployment" CASCADE
;

/* Create Tables */

CREATE TABLE "Deployment"
(
	"Deployment" varchar NULL,
	"DeploymentID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Deployment" ADD CONSTRAINT "PK_Deployment"
	PRIMARY KEY ("DeploymentID")
;