/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Equipment-log-valid" CASCADE
;

/* Create Tables */

CREATE TABLE "Equipment-log-valid"
(
	"Equipment-log-validID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Equipment-log-valid" ADD CONSTRAINT "PK_Equipment-log-valid"
	PRIMARY KEY ("Equipment-log-validID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Equipment-log-valid"
	IS 'XML encodings of EquipmentLog shall conform to the XML form for EquipmentLog specified in the WMDR XML Schema.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;