/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Equipment-log-entries-control-standard" CASCADE
;

/* Create Tables */

CREATE TABLE "Equipment-log-entries-control-standard"
(
	"Equipment-log-entries-control-standardID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Equipment-log-entries-control-standard" ADD CONSTRAINT "PK_Equipment-log-entries-control-standard"
	PRIMARY KEY ("Equipment-log-entries-control-standardID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Equipment-log-entries-control-standard"
	IS 'Where a log entry is a ControlCheckReport, the value of standardType shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/ControlStandardType. '
;