/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Equipment-log" CASCADE
;

/* Create Tables */

CREATE TABLE "Equipment-log"
(
	"Equipment-log" varchar NULL,
	"Equipment-logID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Equipment-log" ADD CONSTRAINT "PK_Equipment-log"
	PRIMARY KEY ("Equipment-logID")
;