/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Eventtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Eventtype"
(
	"EventtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Eventtype" ADD CONSTRAINT "PK_Eventtype"
	PRIMARY KEY ("EventtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Eventtype"
	IS 'Codelist for events at station/platform'
;