/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Exposuretype" CASCADE
;

/* Create Tables */

CREATE TABLE "Exposuretype"
(
	"ExposuretypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Exposuretype" ADD CONSTRAINT "PK_Exposuretype"
	PRIMARY KEY ("ExposuretypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Exposuretype"
	IS 'Codelist for exposure of instrument'
;