/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Facility-log" CASCADE
;

/* Create Tables */

CREATE TABLE "Facility-log"
(
	"Facility-log" varchar NULL,
	"Facility-logID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Facility-log" ADD CONSTRAINT "PK_Facility-log"
	PRIMARY KEY ("Facility-logID")
;