/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Facility-log-entries-event-type" CASCADE
;

/* Create Tables */

CREATE TABLE "Facility-log-entries-event-type"
(
	"Facility-log-entries-event-typeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Facility-log-entries-event-type" ADD CONSTRAINT "PK_Facility-log-entries-event-type"
	PRIMARY KEY ("Facility-log-entries-event-typeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Facility-log-entries-event-type"
	IS 'The value for typeOfEvent in a EventReport shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/EventAtFacility.'
;