/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Facility-type" CASCADE
;

/* Create Tables */

CREATE TABLE "Facility-type"
(
	"Facility-typeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Facility-type" ADD CONSTRAINT "PK_Facility-type"
	PRIMARY KEY ("Facility-typeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Facility-type"
	IS 'The value for facilityType, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/FacilityType.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;