/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Geopositioningmethodtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Geopositioningmethodtype"
(
	"GeopositioningmethodtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Geopositioningmethodtype" ADD CONSTRAINT "PK_Geopositioningmethodtype"
	PRIMARY KEY ("GeopositioningmethodtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Geopositioningmethodtype"
	IS 'Geopositiong Method / Coordinate Source codelist'
;