/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Geopositioning-method" CASCADE
;

/* Create Tables */

CREATE TABLE "Geopositioning-method"
(
	"Geopositioning-methodID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Geopositioning-method" ADD CONSTRAINT "PK_Geopositioning-method"
	PRIMARY KEY ("Geopositioning-methodID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Geopositioning-method"
	IS 'The value for geopositioningMethod, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/GeopoistioningMethod.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;