/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Instrumentcontrolscheduletype" CASCADE
;

/* Create Tables */

CREATE TABLE "Instrumentcontrolscheduletype"
(
	"InstrumentcontrolscheduletypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Instrumentcontrolscheduletype" ADD CONSTRAINT "PK_Instrumentcontrolscheduletype"
	PRIMARY KEY ("InstrumentcontrolscheduletypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Instrumentcontrolscheduletype"
	IS '5-07 Instrument control schedule'
;