/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Instrumentcontrolresulttype" CASCADE
;

/* Create Tables */

CREATE TABLE "Instrumentcontrolresulttype"
(
	"InstrumentcontrolresulttypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Instrumentcontrolresulttype" ADD CONSTRAINT "PK_Instrumentcontrolresulttype"
	PRIMARY KEY ("InstrumentcontrolresulttypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Instrumentcontrolresulttype"
	IS 'Result of an instrument control check'
;