/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Instrumentoperatingstatustype" CASCADE
;

/* Create Tables */

CREATE TABLE "Instrumentoperatingstatustype"
(
	"InstrumentoperatingstatustypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Instrumentoperatingstatustype" ADD CONSTRAINT "PK_Instrumentoperatingstatustype"
	PRIMARY KEY ("InstrumentoperatingstatustypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Instrumentoperatingstatustype"
	IS '5-04 Instrument operating status'
;