/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Localtopographytype" CASCADE
;

/* Create Tables */

CREATE TABLE "Localtopographytype"
(
	"LocaltopographytypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Localtopographytype" ADD CONSTRAINT "PK_Localtopographytype"
	PRIMARY KEY ("LocaltopographytypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Localtopographytype"
	IS 'Local topography codelist (based on Speight 2009)'
;