/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Local-topography" CASCADE
;

/* Create Tables */

CREATE TABLE "Local-topography"
(
	"Local-topographyID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Local-topography" ADD CONSTRAINT "PK_Local-topography"
	PRIMARY KEY ("Local-topographyID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Local-topography"
	IS 'The value for localTopography, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/LocalTopography.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;