/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Measurementunittype" CASCADE
;

/* Create Tables */

CREATE TABLE "Measurementunittype"
(
	"MeasurementunittypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Measurementunittype" ADD CONSTRAINT "PK_Measurementunittype"
	PRIMARY KEY ("MeasurementunittypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Measurementunittype"
	IS 'Codelist for Measurement Unit [according to common code table C-6 (WMO, 2013)]'
;