/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Observation-process" CASCADE
;

/* Create Tables */

CREATE TABLE "Observation-process"
(
	"Observation-processID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Observation-process" ADD CONSTRAINT "PK_Observation-process"
	PRIMARY KEY ("Observation-processID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Observation-process"
	IS 'XML encodings of OM_Observation in WIGOS shall use the WIGOS Process type to describe the om:procedure.'
;