/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Observingfacilitytype" CASCADE
;

/* Create Tables */

CREATE TABLE "Observingfacilitytype"
(
	"ObservingfacilitytypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Observingfacilitytype" ADD CONSTRAINT "PK_Observingfacilitytype"
	PRIMARY KEY ("ObservingfacilitytypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Observingfacilitytype"
	IS 'Codelist for classifications of Observing Facilities (Stations, Platforms)'
;