/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Observedvariabletype" CASCADE
;

/* Create Tables */

CREATE TABLE "Observedvariabletype"
(
	"ObservedvariabletypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Observedvariabletype" ADD CONSTRAINT "PK_Observedvariabletype"
	PRIMARY KEY ("ObservedvariabletypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Observedvariabletype"
	IS 'Observed variable - measurand'
;