/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Observation" CASCADE
;

/* Create Tables */

CREATE TABLE "Observation"
(
	"Observation-segment" varchar NULL,
	"ObservationID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Observation" ADD CONSTRAINT "PK_Observation"
	PRIMARY KEY ("ObservationID")
;