/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Observing-method" CASCADE
;

/* Create Tables */

CREATE TABLE "Observing-method"
(
	"Observing-methodID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Observing-method" ADD CONSTRAINT "PK_Observing-method"
	PRIMARY KEY ("Observing-methodID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Observing-method"
	IS 'The value(s) for observingMethod shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/ObservingMethod.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;