/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Process-valid" CASCADE
;

/* Create Tables */

CREATE TABLE "Process-valid"
(
	"Process-validID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Process-valid" ADD CONSTRAINT "PK_Process-valid"
	PRIMARY KEY ("Process-validID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Process-valid"
	IS 'XML encodings of Process shall conform to the XML form for Process specified in the WMDR XML Schema.'
;