/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Processing-valid" CASCADE
;

/* Create Tables */

CREATE TABLE "Processing-valid"
(
	"Processing-validID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Processing-valid" ADD CONSTRAINT "PK_Processing-valid"
	PRIMARY KEY ("Processing-validID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Processing-valid"
	IS 'XML encodings of Processing shall conform to the XML form for Processing specified in the WMDR XML Schema.'
;