/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Programaffiliation" CASCADE
;

/* Create Tables */

CREATE TABLE "Programaffiliation"
(
	"Programaffiliation" varchar NULL,
	"Programspecificfacilityid" varchar NULL,
	"Reportingstatus" varchar NULL,
	"ProgramaffiliationID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Programaffiliation" ADD CONSTRAINT "PK_Programaffiliation"
	PRIMARY KEY ("ProgramaffiliationID")
;