/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Purposeoffrequencyusetype" CASCADE
;

/* Create Tables */

CREATE TABLE "Purposeoffrequencyusetype"
(
	"PurposeoffrequencyusetypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Purposeoffrequencyusetype" ADD CONSTRAINT "PK_Purposeoffrequencyusetype"
	PRIMARY KEY ("PurposeoffrequencyusetypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Purposeoffrequencyusetype"
	IS '5-03 Instrument specifications. This is a proxy for several more specific elements, here used for Type "PurposeOfFrequencyUseType". PurposeOfFrequencyUseType uses values (observation, telecomms)'
;