/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Qualityflagtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Qualityflagtype"
(
	"QualityflagtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Qualityflagtype" ADD CONSTRAINT "PK_Qualityflagtype"
	PRIMARY KEY ("QualityflagtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Qualityflagtype"
	IS 'Quality Flag codelist. '
;