/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Record-valid" CASCADE
;

/* Create Tables */

CREATE TABLE "Record-valid"
(
	"Record-validID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Record-valid" ADD CONSTRAINT "PK_Record-valid"
	PRIMARY KEY ("Record-validID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Record-valid"
	IS 'XML encodings of WIGOSMetadataRecord shall conform to the XML form for WIGOSMetadataRecord specified in the WMDR XML Schema.'
;