/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Reference-time" CASCADE
;

/* Create Tables */

CREATE TABLE "Reference-time"
(
	"Reference-timeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Reference-time" ADD CONSTRAINT "PK_Reference-time"
	PRIMARY KEY ("Reference-timeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Reference-time"
	IS 'The value for referenceTime, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/ReferenceTime.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;