/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Relativeelevationtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Relativeelevationtype"
(
	"RelativeelevationtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Relativeelevationtype" ADD CONSTRAINT "PK_Relativeelevationtype"
	PRIMARY KEY ("RelativeelevationtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Relativeelevationtype"
	IS 'Relative elevation codelist'
;