/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Relative-elevation" CASCADE
;

/* Create Tables */

CREATE TABLE "Relative-elevation"
(
	"Relative-elevationID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Relative-elevation" ADD CONSTRAINT "PK_Relative-elevation"
	PRIMARY KEY ("Relative-elevationID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Relative-elevation"
	IS 'The value for relativeElevation, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/RelativeElevation.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;