/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Reporting-valid" CASCADE
;

/* Create Tables */

CREATE TABLE "Reporting-valid"
(
	"Reporting-validID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Reporting-valid" ADD CONSTRAINT "PK_Reporting-valid"
	PRIMARY KEY ("Reporting-validID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Reporting-valid"
	IS 'XML encodings of Reporting shall conform to the XML form for Reporting specified in the WMDR XML Schema.'
;