/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Reporting-status" CASCADE
;

/* Create Tables */

CREATE TABLE "Reporting-status"
(
	"Reporting-statusID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Reporting-status" ADD CONSTRAINT "PK_Reporting-status"
	PRIMARY KEY ("Reporting-statusID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Reporting-status"
	IS 'The value for reportingStatus shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/ReportingStatus.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;