/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Representativeness" CASCADE
;

/* Create Tables */

CREATE TABLE "Representativeness"
(
	"RepresentativenessID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Representativeness" ADD CONSTRAINT "PK_Representativeness"
	PRIMARY KEY ("RepresentativenessID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Representativeness"
	IS 'The value for representativeness, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/Representativeness


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;