/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Sampling-valid" CASCADE
;

/* Create Tables */

CREATE TABLE "Sampling-valid"
(
	"Sampling-validID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Sampling-valid" ADD CONSTRAINT "PK_Sampling-valid"
	PRIMARY KEY ("Sampling-validID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Sampling-valid"
	IS 'XML encodings of Sampling shall conform to the XML form for Sampling specified in the WMDR XML Schema.'
;