/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Sourceofobservationtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Sourceofobservationtype"
(
	"SourceofobservationtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Sourceofobservationtype" ADD CONSTRAINT "PK_Sourceofobservationtype"
	PRIMARY KEY ("SourceofobservationtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Sourceofobservationtype"
	IS '5-01 Source of observations in dataset (e.g. manual, automatic, visual)'
;