/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Source-of-observation" CASCADE
;

/* Create Tables */

CREATE TABLE "Source-of-observation"
(
	"Source-of-observationID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Source-of-observation" ADD CONSTRAINT "PK_Source-of-observation"
	PRIMARY KEY ("Source-of-observationID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Source-of-observation"
	IS 'The value(s) for sourceOfObservation shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/SourceOfObservation.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;