/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Surface-cover" CASCADE
;

/* Create Tables */

CREATE TABLE "Surface-cover"
(
	"Surface-coverID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Surface-cover" ADD CONSTRAINT "PK_Surface-cover"
	PRIMARY KEY ("Surface-coverID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Surface-cover"
	IS 'The value for surfaceCover, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/SurfaceCover.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;