/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Surfacecoverclassificationtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Surfacecoverclassificationtype"
(
	"SurfacecoverclassificationtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Surfacecoverclassificationtype" ADD CONSTRAINT "PK_Surfacecoverclassificationtype"
	PRIMARY KEY ("SurfacecoverclassificationtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Surfacecoverclassificationtype"
	IS 'Surface Cover Classification Type'
;