/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Surface-cover-classification" CASCADE
;

/* Create Tables */

CREATE TABLE "Surface-cover-classification"
(
	"Surface-cover-classificationID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Surface-cover-classification" ADD CONSTRAINT "PK_Surface-cover-classification"
	PRIMARY KEY ("Surface-cover-classificationID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Surface-cover-classification"
	IS 'The value for surfaceCoverClassification shall be taken from one of the SurfaceCoverClassificationType codelists at http://codes.wmo.int.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;