/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Surfacecovertype" CASCADE
;

/* Create Tables */

CREATE TABLE "Surfacecovertype"
(
	"SurfacecovertypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Surfacecovertype" ADD CONSTRAINT "PK_Surfacecovertype"
	PRIMARY KEY ("SurfacecovertypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Surfacecovertype"
	IS 'Surface cover types'
;