/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Surface-roughness" CASCADE
;

/* Create Tables */

CREATE TABLE "Surface-roughness"
(
	"Surface-roughnessID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Surface-roughness" ADD CONSTRAINT "PK_Surface-roughness"
	PRIMARY KEY ("Surface-roughnessID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Surface-roughness"
	IS 'The value for surfaceRoughness shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/SurfaceRoughnessDavenport.'
;