/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Surfaceroughnesstype" CASCADE
;

/* Create Tables */

CREATE TABLE "Surfaceroughnesstype"
(
	"SurfaceroughnesstypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Surfaceroughnesstype" ADD CONSTRAINT "PK_Surfaceroughnesstype"
	PRIMARY KEY ("SurfaceroughnesstypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Surfaceroughnesstype"
	IS '4-06'
;