/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Territorytype" CASCADE
;

/* Create Tables */

CREATE TABLE "Territorytype"
(
	"TerritorytypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Territorytype" ADD CONSTRAINT "PK_Territorytype"
	PRIMARY KEY ("TerritorytypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Territorytype"
	IS 'WMO Territories (territory of origin of the data)'
;