/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Territory-name" CASCADE
;

/* Create Tables */

CREATE TABLE "Territory-name"
(
	"Territory-nameID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Territory-name" ADD CONSTRAINT "PK_Territory-name"
	PRIMARY KEY ("Territory-nameID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Territory-name"
	IS 'The value for territoryName shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/TerritoryName.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;