/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Timestampmeaningtype" CASCADE
;

/* Create Tables */

CREATE TABLE "Timestampmeaningtype"
(
	"TimestampmeaningtypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Timestampmeaningtype" ADD CONSTRAINT "PK_Timestampmeaningtype"
	PRIMARY KEY ("TimestampmeaningtypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Timestampmeaningtype"
	IS 'Time stamp meaning codelist'
;