/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Time-encoding" CASCADE
;

/* Create Tables */

CREATE TABLE "Time-encoding"
(
	"Time-encoding" varchar NULL,
	"Time-encodingID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Time-encoding" ADD CONSTRAINT "PK_Time-encoding"
	PRIMARY KEY ("Time-encodingID")
;