/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Timezonetype" CASCADE
;

/* Create Tables */

CREATE TABLE "Timezonetype"
(
	"TimezonetypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Timezonetype" ADD CONSTRAINT "PK_Timezonetype"
	PRIMARY KEY ("TimezonetypeID")
;