/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Time-stamp-meaning" CASCADE
;

/* Create Tables */

CREATE TABLE "Time-stamp-meaning"
(
	"Time-stamp-meaningID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Time-stamp-meaning" ADD CONSTRAINT "PK_Time-stamp-meaning"
	PRIMARY KEY ("Time-stamp-meaningID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Time-stamp-meaning"
	IS 'The value for temporalReportingTimeStampMeaning, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/TimeStampMeaning.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;