/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Topographic-context" CASCADE
;

/* Create Tables */

CREATE TABLE "Topographic-context"
(
	"Topographic-contextID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Topographic-context" ADD CONSTRAINT "PK_Topographic-context"
	PRIMARY KEY ("Topographic-contextID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Topographic-context"
	IS 'The value for topographicContext, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/wmdr/TopographicContext.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;