/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Topographiccontexttype" CASCADE
;

/* Create Tables */

CREATE TABLE "Topographiccontexttype"
(
	"TopographiccontexttypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Topographiccontexttype" ADD CONSTRAINT "PK_Topographiccontexttype"
	PRIMARY KEY ("TopographiccontexttypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Topographiccontexttype"
	IS 'Topographic Context codelist (based on Hammond 1954)'
;