/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Unit-of-measure" CASCADE
;

/* Create Tables */

CREATE TABLE "Unit-of-measure"
(
	"Unit-of-measureID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Unit-of-measure" ADD CONSTRAINT "PK_Unit-of-measure"
	PRIMARY KEY ("Unit-of-measureID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Unit-of-measure"
	IS 'The value for uom, if supplied, shall be taken from the code table published online at http://codes.wmo.int/common/Unit.


This codelist is also described in the WIGOS Metadata Standard, Chapter VII.'
;