/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Wmoregiontype" CASCADE
;

/* Create Tables */

CREATE TABLE "Wmoregiontype"
(
	"WmoregiontypeID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Wmoregiontype" ADD CONSTRAINT "PK_Wmoregiontype"
	PRIMARY KEY ("WmoregiontypeID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Wmoregiontype"
	IS 'WMO Regions (region of origin of data)'
;