/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-May-2022 21:43:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Xsd-valid" CASCADE
;

/* Create Tables */

CREATE TABLE "Xsd-valid"
(
	"Xsd-validID" varchar NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Xsd-valid" ADD CONSTRAINT "PK_Xsd-valid"
	PRIMARY KEY ("Xsd-validID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Xsd-valid"
	IS 'XML encodings of WMDR shall validate against the WMDR XML Schema (xsd).'
;