sprite $pygeoapi [66x63/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAABFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFAAAB4BB49AAFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFAAAFFFFFFFFFAAAAFFFFFAAAAFFFFFFFFFDA9FFFFFFFFFFFFFFF
FFFFFFFFFFFFFAAAAAAFFFFFFFAAAAFFFFFFAAAFFFFFFFFAAAAAAFFFFFFFFFFFFF
FFFFFFFFFFFFAAAAAAAAFFFFFFAAAAFFFFFFAAAFFFFFFFAAAAAA9AFFFFFFFFFFFF
FFFFFFFFFFFAAAAAAAAAAFFFFFAAAAFFFFFFAAAFFFFFFAAAAAAAAAAFFFFFFFFFFF
FFFFFFFFFFAAAAAAAAAAAAFFFAAAAAFFFFFFAAAAFFFFAAAAAAAAAAAAFFFFFFFFFF
FFFFFFFFFAAAAAAAAAAAAAAAAAAAAAFFFFFFAAAAAAAAAAAAAACAAAAAAFFFFFFFFF
FFFFFFFFAAAAAAAFAAAAAAAAAAAAAAFFFFFFAAAAAAAAAAAAAFAAAAAAAFFFFFFFFF
FFFFFFFFAAAAAAFFFAAAAAAAAAAAAFFFFFFFAAAAAAAAAAAAFFFAAAAAAFFFFFFFFF
FFFFFFFFAAAAAFFFFFAAAAAAAAAAAFFFFFFFFAAAAAAAAAAFFFFFAAAAAFFFFFFFFF
FFFFFFFFAAAAAFFFFFFAAAAAAAAAFFFFFFFFFFAAAAAAAAFFFFFFAAAAAFFFFFFFFF
FFFFFFFFAAAAAAFFFFFFAAAAAAFFFFFCCBFFFFFBAAAAAFFFFFFAAAAAAFFFFFFFFF
FFFFFFFFAAAAAAAFFFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFFFAAAAAABFFFFFFFFF
FFFFFFFFFAAAAAAAFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFAAAAAAAAFFFFFFFFF
FFFFFFFFFFAAAAAAFFFFFFFFCCCCCCCCCCCCCCCCCFFFFFFFFAAAAAAAFFFFFFFFFF
FFFFFFFFFFFAAAAABFFFFFFCECCCCCCCCCCCCCCCCCFFFFFFFAAAAAAFFFFFFFFFFF
FFFFFFFFFFFFAAAADFFFFFCCCCCCDCCCCCCCCCCCCCCFFFFFFAAA9AFFFFFFFFFFFF
FFFFFFFFFFFFFAAA9FFFFFCCCCCCCFCCCCCFCCCCCCCFFFFFFAAAAFFFFFFFFFFFFF
FFFFFFFFFFFFAAAA9FFFFCCCCCCFCCCCCCCCCFCCCCCCFFFFFAAAAFFFFFFFFFFFFF
FFFFFFFFFFAAAAAA9FFFFCCCCCFCCCCCCCCCCCFCCCCCFFFFFAAAAAAFFFFFFFFFFF
FFFAAAAAAAAAAAAAFFFFFCCCCFFFCCCCCCCCCCDFCCCCCFFFFAAAAAAAAAAAAAFFFF
FFAAAAAAAAAAAAAAFFFFBCCCCFCCCCCCCCCCCCCFCCCCCFFFFAAAAAAAAAAAAAAFFF
FFAAAAAAAAAAAA39FFFFCCCCFFCCCCCCFCCCCCCFFCCCCFFFFFAAAAAAAAAAAAAFFF
FFAAAAAAAAAAAAAFFFFFCCCCFFCCCCFFFFFCCCCFFCCCCFFFFFFA4AAAAAAAAAAFFF
FFAAAAAAAAAAAFFFFFFFCCCFFFCCCBFFFFFFCCCFFFCCCFFFFFFFAAAAAAAAAAAFFF
FFAAAAFFFFFFFFFFFFFFCCCFFFCCCCFFFFFCCCCFFFCCCFFFFFFFFFFFFFFFAAAFFF
FFAAAAFFFFFFFFFFFFFFCCCCFFCCCCCFFFFCCCCFFCCCCFFFFFFFFFFFFFFFAAAFFF
FFAAAAFFFFFFFFFFFFFFCCCCFFCCCCCCCCCCCCCFFECCCFFFFFFFFFFFFFFFAAAFFF
FFAAAAFFFFFFFFFFFFFFCCCCFFCCCCCCCCCCCCCFFCCCCFFFFFFFFFFFFFFFAAAFFF
FFAAAAAAAAAAAFFFFFFFCCCCCFFCCCCCCCCCCCFFCCCCCFFFFFFFAAAAAAAAAAAFFF
FFAAAAAAAAAAAAAFFFFFFCCCCFFCCCCCCCCCCCFFBCCCFFFFFFFAAAAAAAAAAAAFFF
FFAAAAAAAAAAAAAAFFFFFCCCCCFFFCCCBCCCCFFACCCCFFFFFFAAAAAAAAAAAAAFFF
FFAAAAAAAAAAAAAAFFFFFCCCCBFFFFFCCCFFFFFCCCCCFFFFFAAAAAAAAAAAAAAFFF
FFFAAAAAAAAAAAAAFFFFFFCCCCCFFFFFFFFFFFCCCCCFFFFFFAAAAA9AAAAAAAFFFF
FFFFFFFFFFAAAAAA9FFFFFCCCCCCFFFFFFFFFFBCCCCFFFFFFAAAAAAFFFFFFFFFFF
FFFFFFFFFFFFAAAA9FFFFFFCCCCCFFFFFFFFFCCCCCFFFFFFFAAAAFFFFFFFFFFFFF
FFFFFFFFFFFFFAAA9FFFFFFCCCCCCFFFFFFFCCCCCCFFFFFFFAAAAFFFFFFFFFFFFF
FFFFFFFFFFFFAAAADFFFFFFFCCCCCCFFFFFCCCCCCFFFFFFFFAAA9AFFFFFFFFFFFF
FFFFFFFFFFFAAAAABFFFFFFFFCCCCCCFFFCBCCCCCFFFFFFFFAAAAAAFFFFFFFFFFF
FFFFFFFFFFAAAAAAFFFFFFFFFCCCCCCCFCCCCCCCFFFFFFFFFAAAAAAAFFFFFFFFFF
FFFFFFFFFAAAAAAAFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFAAAAAA9AFFFFFFFFF
FFFFFFFFAAAAAAAFFFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFFFAAAAAAAFFFFFFFFF
FFFFFFFFAAAAAAFFFFFFAAAAAAFFCCCCCCCCCFFFAAAAAFFFFFFAAAAAAFFFFFFFFF
FFFFFFFFAAAAAFFFFFFAAAAAAAAAFCCCCCCCFFAAAAAAAAFFFFFFAAAAAFFFFFFFFF
FFFFFFFFAAAAAFFFFFAAAAAAAAAAAFCCCCCFFAAAAAAAAAAFFFFFAAAAAFFFFFFFFF
FFFFFFFFAAAAAAFFFAAAAAAAAAAA9FFCCCFFAAAAAAAAAAAAFFFAAAAAAFFFFFFFFF
FFFFFFFFAAAAAAAFAAAAAAAAAAAAAAFFFFFFAAAAAAAAAAAAAFAAAAAAAFFFFFFFFF
FFFFFFFFFAAAAAAAAAAAAAAAAAAAAAFFFFFFAAAAAAAAAAAAAABAAAA8AFFFFFFFFF
FFFFFFFFFFAAAAAAAAAAAAFFFAAAAAFFFFFFAAAAFFFFAAAAAAAAAA9AFFFFFFFFFF
FFFFFFFFFFFAAAAAAAAAAFFFFFAAAAFFFFFFAAAFFFFFFAAAAAAAA9AFFFFFFFFFFF
FFFFFFFFFFFFAAAAAAAAFFFFFFAAAAFFFFFFAAAFFFFFFFAAAAAA9AFFFFFFFFFFFF
FFFFFFFFFFFFFAAAAAAFFFFFFFAAAAFFFFFFAAAFFFFFFFFAAAAAAFFFFFFFFFFFFF
FFFFFFFFFFFFFFAAAFFFFFFFFFAAAAFFFFFAAAAFFFFFFFFFAA9FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF9AAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}