<template>
  <v-container>
  <v-row>
    <v-col :cols=6>
      <v-card style="min-height: 500px;">
        <v-card-title>Select location</v-card-title>
        <v-card-text style="height: 500px;"><base-map @mapLoaded='onMapLoaded' @click="selectGeometry"></base-map></v-card-text>
      </v-card>
    </v-col>
    <v-col :cols=6>
      <v-row><v-col :cols=12><v-text-field label="Longitude" v-model="geom.geometry.coordinates[0]" type="number" hint="Longitude (-180 to 180)" persistent-hint></v-text-field></v-col></v-row>
      <v-row><v-col :cols=12><v-text-field label="Latitude" v-model="geom.geometry.coordinates[1]" type="number" hint="Latitude (-90 to 90)" persistent-hint></v-text-field></v-col></v-row>
      <v-row><v-col :cols=12></v-col><v-text-field label="WKT" v-model="geom.properties.wkt" hint="autogenerated" readonly persistent-hint></v-text-field></v-row>
    </v-col>
  </v-row>
  </v-container>
</template>

<script>
  import "leaflet/dist/leaflet.css";
  import L from 'leaflet';
  import {defineComponent, ref, computed, context, emit, watch} from 'vue';
  import {VCard, VCardTitle, VCardItem, VCardText, VContainer, VRow, VCol, VTextField} from 'vuetify/lib/components';
  import * as Wkt from 'wicket';
  import BaseMap from '@/web-components/maps/base-map.vue';

  export default defineComponent({
    name: 'GeometryPicker',
    props:{
      geometry_type: {
        type: String,
        default: "point",
      },
      modelValue:  {
        type: String,
        default: ""
      }
    },
    components: {
      VCard,
      VCardTitle,
      VCardItem,
      VCardText,
      VContainer,
      VRow,
      VCol,
      VTextField,
      BaseMap
    },
    emits: ["update:modelValue"],
    setup(props, {emit}){
      const enabled = ref(true)
      const geom = ref({
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [null, null]
        },
        properties: {
          wkt: ""
        }
      })
      const map = ref(null);
      const geojsonLayer = ref(null);
      const wkt = ref("");
      const onMapLoaded = async (mapInstance) => {
        map.value = mapInstance;
        geojsonLayer.value = L.geoJSON().addTo(map.value);
        // check if we have data to add
        if( geom.value.geometry.coordinates[0] != null & geom.value.geometry.coordinates[1] != null ){
          geojsonLayer.value.addData( geom.value);
          map.value.setView( [ geom.value.geometry.coordinates[1], geom.value.geometry.coordinates[0]])
        }
      };
      const selectGeometry = (e) => {
        if (map.value.dragging._draggable._moved || ! enabled.value ) {
         // If the user has moved the map do nothing
          return;
        }
        const point = map.value.mouseEventToLatLng(e);
        var _wkt = new Wkt.Wkt();
        if (props.geometry_type === "point"){
          geom.value.geometry.coordinates = [point.lng, point.lat];
          _wkt.read(JSON.stringify(geom.value));
          geom.value.properties.wkt = "SRID=4326; " + _wkt.write();
          updateMap(map);
        }
      };

      // watch for changes to reactive geom
      watch(() => geom, (newVal) => {
        // update the wkt
        var _wkt = new Wkt.Wkt();
        _wkt.read(JSON.stringify(geom.value));
        geom.value.properties.wkt = "SRID=4326; " + _wkt.write();
        updateMap(map);
      }, { deep: true });

      // watch for changes to props
      watch( () => props.modelValue, (newValue) => {
          if( newValue ){
            geom.value.properties.wkt = newValue;
            const coords = newValue.match(/POINT\(([-\d\.]+)\s+([-\d\.]+)\)/);
            const latlng = [parseFloat(coords[1]), parseFloat(coords[2])];
            geom.value.geometry.coordinates = latlng;
            if(map.value){updateMap(map)};
          }
        },{immediate: true}
      )

      const updateMap = (map) => {
        if( map.value ){
          if( geom.value.geometry.coordinates[0] != null & geom.value.geometry.coordinates[1] != null ){
            geojsonLayer.value.clearLayers();
            geojsonLayer.value.addData( geom.value);
            map.value.setView( [ geom.value.geometry.coordinates[1], geom.value.geometry.coordinates[0]])
            emit("update:modelValue", geom.value.properties.wkt);
          }
        }
      };
      return {map, onMapLoaded, selectGeometry, geom}
    }
  });

</script>
